application: aesc
version: 1
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
  - url: /favicon.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon.ico
  
  - url: /static/images/fileicons/.*
    script: core/zip_handler.py
    
  - url: /fckeditor/.*
    script: core/zip_handler.py
  
  - url: /static
    static_dir: static
 
  - url: /admin/.*
    script: common/appenginepatch/main.py
    login: required
 
  - url: /.*
    script: common/appenginepatch/main.py

  - url: /remote_api
    script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
    login: admin
    
    

    
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 )$
